### ISSUE TITLE
installing via git results in empty package

### ISSUE THREAD

**Issue by robertkowalski** [EOSIO/eosjs#143]
npm supports git, which is handy if you want to have the latest version.

seems it results in broken packages for eosjs:

```
npm i --save https://github.com/EOSIO/eosjs
```

**Comment by jcalfee** [comment]
That is not going to work because the generated es2015 code is not checked in..  Checking that in could really mess up the diff ..  Npm i git is looking at the .npmignore file and it is not including the regular source code either.  I think you'll need to clone and run npm build or npm build_browser..

**Comment by robertkowalski** [comment]
hm yeah, thats odd, and `install` hooks are not fancy either.

for my use case, probably the best it to clone regularly with git, then link the package with npm link.

thx for the feedback!
