### ISSUE TITLE
An analog of the "--force-unique" option?

### ISSUE THREAD

**Issue by IvanYakimov** [EOSIO/eosjs#193]
I am trying to send several actions with the same payload (duplicates) to the nodeos using eosjs. 
If I used cleos I would apply "--force-unique flag" to my "cleos push action" request, but I couldn't find any possibility of doing so in eosjs.
Please, tell me how can I send multiple duplicate actions in eosjs in a right way?

**Comment by jcalfee** [comment]
It looks like cleos uses a `nonce` action that works on the `eosio.null` account.  You can provide a unique  value each time.  If you have a `eosio.null` account in nodeosd with a ABI deployed that defines `nonce` it will work.  You could setup a test account like this with any name and add your own nonce value.  Are you doing this only for testing?

**Comment by kasperfish** [comment]
is this already implemented?
![image](https://user-images.githubusercontent.com/5130772/41812353-9bc4cc1e-7721-11e8-8474-d117dba1a09c.png)

**Comment by jcalfee** [comment]
I found an issue using the nonce in a transaction, your right it is not available there.  I'll have a look.  In the mean time, you could create your transaction as an object and pass it in to `eos.transaction` directly.  The nonce should look like this (replace inita with your account):

```js
{"account":"eosio.null","name":"nonce","authorization":[{"actor":"inita","permission":"active"}],"data":"0131"}
```

This could be another problem. Make sure you get to review the transaction your sending to the blockchain for any duplicate from(s) in the transfer actions..

**Comment by kasperfish** [comment]
thanks @jcalfee , however changing the memo should work too? well, if the memo is different then the transfer/transaction is different too. I have tried this and it's not possible either. Or Am I missing something?

**Comment by jcalfee** [comment]
What is the error?  I have EOSIO/eos open, I do a few searches and find it..

**Comment by ekkis** [comment]
> {"account":"eosio.null","name":"nonce","authorization":[{"actor":"inita","permission":"active"}],"data":"0131"}

a little confused... this calls a method called "nonce" in a contract called "eosio.null" -- supposing I have my own contract/method I need to call and am having the OP's problem of getting duplicate transactions, how would I add a nonce to the transaction to make it unique?

**Comment by bakasura980** [comment]
Hey @ekkis, How nonce transactions works:
You can have multiple actions in one transaction. In order to get the duplicate error, all of your actions are actually the same (same arguments).

When you are calling lets say your custom method with a nonce transaction the resulted transactions is something like :
```
transaction = {
actions:[
"mycustomAccount": "customAction",
"eosio.null": "nonceAction" // nonceAction should be an unique value (Date.now)
]
}
```

In this way actually your transaction becomes unique. Yes you are processing your custom action with the same arguments, but you are calling eosio.null each time with different nonce and actually your whole transaction becomes unique.

You can check eoslime. This is a javascript framework on top of eosjs and there is nonce transactions support.
You just should do 
```
myContract.myAction(arguments, {unique: true}) 
```
in order to solve the duplicate transaction error
