### ISSUE TITLE
use getTableRows to get list of all tokens on EOS

### ISSUE THREAD

**Issue by asghaier76** [EOSIO/eosjs#254]
Is there a specific table to read using getTableRows to get the list of all tokens deployed on EOS

**Comment by zero2pi** [comment]
each of the tokens are using their own contracts !!! so dont think it would be possilble to do something like that !!!

**Comment by jgiszczak** [comment]
There is no such possibility.  The token contract can be loaded into any account at any time.  There is no reasonable method to discover all of the tables created by such actions.  The only way to find them all is an exhaustive search, and even that is unreliable as the token contract may be modified before being loaded, changing table names.

The requested functionality will not be provided.

**Comment by jcalfee** [comment]
I'm sure a coin registry smart contract will emerge at some point.  This way users have some well known place or places to submit their coin and set some basic information about their token.

**Comment by ekkis** [comment]
I grabbed the account CoinRegistry today.  this may not be the best place to ask but I'll start here.  would it make sense to require that contract owners include a table in their contracts listing the token information for the tokens they manage e.g. symbol, decimals, desc so that my contract can query theirs for that information and aggregate it, or would it be better to let anyone managed it on a website?

**Comment by ekkis** [comment]
I've also made a proposal to standardise the discovery process, which would allow aggregation programatically: https://github.com/EOSIO/eosio.contracts/issues/200
