### ISSUE TITLE
abicache isn't working

### ISSUE THREAD

**Issue by alexey4eg** [EOSIO/eosjs#260]
The problem is that config which is passed to structs by abicache doesn't have referece to abicache. Therefore attempt to use abicache gives null reference error.
This can be replicated if u try to send propose to a multisig with action to a some custom account
  eos.fc.abiCache.abi('some_custom_contract', abi) doens't help

**Comment by alexey4eg** [comment]
fix proposal https://github.com/alexey4eg/fix_eosjs/commit/ce8388dfb3d811cce39047299901a5c338e61ed8

**Comment by jcalfee** [comment]
Interesting .. This is probably a better place to set the abiCache reference.  The fix proposal is a little clearer .. I'm not sure how it fixes anything though.  This is the only place AbiCache is created the abiCache reference is set after:

https://github.com/EOSIO/eosjs/blob/f466d585b3f4f5ea1eba0eaf15eee80610cc6b05/src/index.js#L66-L67

I'll probably take the code change.  I will work-up the example you described first though and test it.

**Comment by jcalfee** [comment]
It would be nice to stop cloning the `config` object and make the behavior more flexible..  So I made an adjustment in the commit above.  I'm not sure if that will fix your issue since it did not fix anything in node v8+ or es2015 version code.

Keep in mind, you will probably see many errors like the one your seeing unless you transpile the code:
https://github.com/EOSIO/eosjs/blob/v15.0.6/package.json#L16
https://github.com/EOSIO/eosjs/blob/v15.0.6/package.json#L62-L77

**Comment by jcalfee** [comment]
Eosjs@16.0.0 is published .. Those changes should help..
