### ISSUE TITLE
modules override bug

### ISSUE THREAD

**Issue by gaboesquivel** [EOSIO/eosjs#267]
There's a problem with the line https://github.com/EOSIO/eosjs/blob/master/src/index.js#L95 as it overrides `eos.modules` .  perhaps we want to use [deepmerge](https://www.npmjs.com/package/deepmerge) or [lodash.merge](https://www.npmjs.com/package/lodash.merge) instead.

Overall a better code organization for this particular feature would be nice. 

```js	
const eos = require('eosjs')
console.log(`typeof Eos.modules.api =  ${typeof eos.modules.api}`)  // function
console.log(Object.keys(eos.modules))  // [ 'format', 'api', 'ecc', 'json', 'Fcbuffer' ]

const eos2 = eos({httpEndpoint: 'http://jungle.eosio.cr'})
console.log(`typeof Eos.modules.api =  ${typeof eos2.modules.api}`)  // undefined
console.log(Object.keys(eos2.modules))  // ['format']
```

Also I recommend not use `merge` as variable or key name as this is very commonly used as method name. 

I want to confirm this is a bug and not expected behavior before submitting patch for it.

**Comment by jcalfee** [comment]
A better design would be nice.. Keep in mind `Eos.modules` are the static modules and `eos.modules` is the instance of `eos` after it is configured and not the same thing.  The only reason `eos.modules` exists is to make it easier for apps that use dependency injection to access `eos.modules.format`..

One solution to simplify this might be to make it the exact same reference: `Eos.modules === eos.modules` .. `Eos.modules` should remain because non of those references require configuration.

**Comment by gaboesquivel** [comment]
oh, I see, I totally missed static vs instance.
