### ISSUE TITLE
getActions function returns an empty array

### ISSUE THREAD

**Issue by VassalX** [EOSIO/eosjs#294]
I am developing a simple bot, using eosjs and i cannot get the list of latest actions from any account. I am confused and i don't understand what am i doing wrong? Here is an example:

```javascript
const Eos = require('eosjs-api');
const config = {
    expireInSeconds: 60,
    broadcast: true,
    debug: false,
    sign: true,
    httpEndpoint: 'http://mainnet.eoscalgary.io:80',
};
const eos = Eos(config);
eos.getActions("bitfinexcw15", 0, 10, (err, res) => {
    if(err){
        console.log(err);
    } else {
        console.log(res);
    }
});
```

And that's what i get: 

`{ actions: [], last_irreversible_block: 10102319 }`

**Comment by jcalfee** [comment]
Actions is a heavy weight API call for the server using RAM in the API node so I'm not aware of any public end-points supporting it.  Seems like someone would build an index for this and support it though.  You can however enable and use it on your full node.  Check the usage for nodeos, it is called `--filter-on` ..

Also consider latest solution in the new reactjs templates.  These use docker and a database to collect data like this.  The repositories come up when searching EOSIO repositories on github for "dapp".

https://github.com/EOSIO/eosio-project-boilerplate-simple
https://github.com/EOSIO/eosio-project-demux-example

Please let us know if you find support for indexing all actions in this way.  The get_actions API call might be better suited for some dapps.  That would mean the API node needs to index every action on every account even if they will never be used unless they had a service you could provide for maybe staking some tokens.  In the mean time, getting dapps a full stack is a better way to prioritize because it provides solutions to many things including this one.

**Comment by melvjoshua** [comment]
Anybody can help me? I have some problems like this.
When I called get_actions from my middleware (developed with php), it returns
`{ actions: [], last_irreversible_block: 10102319 }`

But when I called the API directly with
`curl http://127.0.0.1:8888/v1/history/get_actions -d '{"account_name":"idxtester121","pos":-1,"offset":-20}'`

it will return the history
