### ISSUE TITLE
tps is very low, while trying to benchmark the performance

### ISSUE THREAD

**Issue by liliyongleo** [EOSIO/eosjs#303]
We've tried to store some table into EOS via smart contract, and using eosjs as API interface. all thing work. but when we do the performance test, the eosjs consume lots of cpu, and prompt following message:
![default](https://user-images.githubusercontent.com/14865405/44008939-dadbf130-9eda-11e8-888e-bdd0d270ff9c.png)

Seems like it took time to sign the transactions, if lots of requests flow into eosjs. Could anyone can help? Thanks.

**Comment by jcalfee** [comment]
Sure, I have an idea .. Changing the signature algorithm still needs a little more research.

ref: https://github.com/EOSIO/eosjs-ecc/issues/20#issuecomment-397506197

**Comment by chris-allnutt** [comment]
@liliyongleo what exactly are you trying to performance test?

**Comment by chris-allnutt** [comment]
@liliyongleo I would recommend creating a bunch of transactions using broadcast false then submitting them all at once.  You'll find the thruput without signing as part of the test.

If you're just wondering about how many actions you can handle then you could put a bunch of actions into a single transaction.  You'll only sign it once so that won't be a factor BUT the actions will execute in sequence in the contract so you can see how it does.

**Comment by liliyongleo** [comment]
Thanks, chris. We've tried put a bunch of actions into a single transaction. It helps. But the problem is: it requires same private key for all these actions. In our senario, the requests can be from different account.

**Comment by jcalfee** [comment]
@chris-allnutt I'm wondering if Aarin can tell us why nodeos differs from the rfc6979 signing algorithm only by starting its nonce starts with 1 (instead of zero).  That actually skips a step in the signature discovery process.  So it would be good to know why nodeoes starts its nonce with 1.

Assuming this comment is correct, this finds that nodeos starts the nonce ("k") with 0: https://github.com/EOSIO/eosjs-ecc/issues/20#issuecomment-397506197

This will give me some safe options to use so I can performance test..
