### ISSUE TITLE
EOSJS transfer can not work in develop local

### ISSUE THREAD

**Issue by songjim** [EOSIO/eosjs#330]
hi,guys.
i can run in commond with ```cleos --url http://nodeos:8888 --wallet-url http://127.0.0.1:9876 push action song transfer '{"from":"eosio","to":"currency","quantity":"20.0000 EOS","memo":"1234"}' --permission eosio -j ``` and it works. but when i run with eosjs ,it doesn't work. here is my code 
```this.client.transfer({from: 'eosio', to: 'currency', quantity: "20 EOS", memo, option});```
and the code return is  ![image](https://assets.bitrabbit.com/upload/480e2de1-9783-46ef-8024-78291abb6721.jpg) 
can somebody help me?

**Comment by amolmaid** [comment]
Hi @songjim ,

   I am sure the issue is with your **quantity**  as you should provide correct precision(number of zeros after period=.) while making transaction, same as of the time you created the token.
  Also if you check your nodeos instance running terminal, you could see the precise error msg for that, something like `symbol precision mis-match`.
   And btw nice wallpaper(luffy's ... ;) ) Good luck

**Comment by songjim** [comment]
thx @amolmaid
