### ISSUE TITLE
is there anyway to transfer ram！

### ISSUE THREAD

**Issue by iindajingjing** [EOSIO/eosjs#340]
such as :
       I have 100M ram and I want to transfer 50M to  other person .is there anyway to transfer ram！ @jcalfee

**Comment by jcalfee** [comment]
I only see this feature for band-width: `delegatebw` .. There are functions to buy and sell ram only:
https://github.com/EOSIO/eosio.contracts/blob/v1.3.0/eosio.system/src/eosio.system.cpp#L299

If they use the RAM you'll never get it back unless they free it.  So I that does not make since.

It could be possible to create a generic table in you own account and implement a quota for them.  You'll have to consider if that will work in terms of the ABI and parameters.  You'll probably see only serilized data in your account because the ABI is in their account.  Also, get table rows will not work well.

**Comment by jcalfee** [comment]
Are you following the EOS REX contract from bytemaster?  I wonder if they plan to include RAM..

**Comment by iindajingjing** [comment]
@jcalfee  thank you so much 。
