### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_1_eosjs__.Rpc is undefined 

### ISSUE THREAD

**Issue by feekayo** [EOSIO/eosjs#405]
**Version of EOSJS**
^20.0.0-beta2

**Describe the bug**
I keep getting this error on react everytime I try to initiate a transaction witth EOSJS 

**To Reproduce**
```
import {Api, Rpc, SignatureProvider} from 'eosjs'
import  shajs from 'sha.js'

//httpEndpoint
const httpEndpoint = "http://127.0.0.1:8888";
const ContractName = "cx";

//main action call to blockchain
async function takeAction(action, dataValue) {
  const privateKey = localStorage.getItem("KEY");
  const rpc = new Rpc.JsonRpc();
  const signatureProvider = new SignatureProvider([privateKey]);
  const api = new Api({ rpc, signatureProvider, textDecoder: new TextDecoder(), textEncoder: new TextEncoder() });

  // Main call to blockchain after setting action, account_name and data
  try {
    const resultWithConfig = await api.transact({
      actions: [{
        account: ContractName,
        name: action,
        authorization: [{
          actor: localStorage.getItem("USERNAME"),
          permission: 'active'
        }],
        data: dataValue,
      }]
    }, {
      blocksBehind: 3,
      expireSeconds: 30,
    });
    return resultWithConfig;
  } catch (err) {
    throw(err)
  }
}
```

**Expected behavior**
I'm really new to eosjs and would really love to get past this asap

**Comment by c0d3ster** [comment]
Hello feekayo,

We have made a few breaking changes moving from beta1->beta2, which have been outlined in the PR [here](https://github.com/EOSIO/eosjs/pull/402) along with appropriate updates to the README.  Included in those changes is a refactor of the JsonRpc and JsSignatureProvider classes and how they're imported, so please update your code according to the new documentation and let us know if you have any further issues.  We will also be doing some release notes outlining these changes today in order to minimize any confusion on the changes from beta1->beta2.

**Comment by iKest** [comment]
no Rpc., just jsonRpc. or use 
import * as Eos from 'eosjs'

**Comment by iKest** [comment]
no Rpc., just jsonRpc. or use 
import * as Eos from 'eosjs'

**Comment by c0d3ster** [comment]
@iKest actually, you won't have to use JsonRpc. syntax anymore either.  The interfaces have been pulled out of the eosjs_jsonrpc file now, so the syntax is now simply `const rpc = new JsonRpc(httpEndpoint)`.  The second issue for @feekayo is he must import the signature provider as `JsSignatureProvider`, but this is also outlined in our README and PR notes.

**Comment by feekayo** [comment]
Thanks for your assistance. You guys are doing an exceptional job...

I've refactored my code.. Now I'm getting an error: fetching the abi
(internal service error) for my smart contract. Its progress I guess...

**Comment by c0d3ster** [comment]
Thanks, happy to help eager developers out!
Many of the errors from the chain are obfuscated to "Internal Service Errors" for security purposes as of right now, but since you are running a local node you should be able to see the specifics of that error message in the terminal running your local node.  Without seeing the updated code, I can't say for sure what the error might be, but there's two things that come to mind right off the bat:

1.  Ensure you are using the correct httpEndpoint when intializing JsonRpc because this endpoint will be called upon to retrieve the abis
1. Ensure your transaction is not malformed and the contract actually exists on your local chain,  the contractName and action need to reference a contract you've created when initializing your chain (i.e. `account: "eosio.token", name: "transfer"`) [here's](https://github.com/EOSIO/eosio.contracts) a reference for these contracts.

**Comment by feekayo** [comment]
![screenshot from 2018-10-22 14-57-51](https://user-images.githubusercontent.com/16284678/47413511-5d7e6280-d766-11e8-90d2-49d00b359777.png)
This is me pushing the contract to my local node

![screenshot from 2018-10-22 14-58-25](https://user-images.githubusercontent.com/16284678/47413526-68d18e00-d766-11e8-8657-afc774f2baec.png)
this is the error log on my client browswer

![screenshot from 2018-10-24 08-27-57](https://user-images.githubusercontent.com/16284678/47413656-c5cd4400-d766-11e8-8c10-dc5909fe719c.png)
This is the network trace on mozilla..

I know I am definitely doing something wrong... I have made the updates you asked for in my code.. Still getting the same error.

Thanks for your assistance

**Comment by iKest** [comment]
catch the error with:
catch (e) {
  console.log('\nCaught exception: ' + e);
  if (e instanceof RpcError)
    console.log(JSON.stringify(e.json, null, 2);
}

for more error information

**Comment by feekayo** [comment]
![screenshot from 2018-10-24 09-16-04](https://user-images.githubusercontent.com/16284678/47416374-7a6a6400-d76d-11e8-9a3f-589680ebd3d2.png)

Here's what I got

**Comment by feekayo** [comment]
![screenshot from 2018-10-24 09-47-52](https://user-images.githubusercontent.com/16284678/47418450-08e0e480-d772-11e8-92b0-ab868935a4dc.png)

The error on my local node from the get_abi function

![screenshot from 2018-10-24 09-48-42](https://user-images.githubusercontent.com/16284678/47418451-09797b00-d772-11e8-9a1e-11de65f87c8b.png)

The error on my log from get_abi function

I unlocked my wallets before carrying out the actions
