### ISSUE TITLE
How to calculate transactionId in tag@v20.0.0-beta2?

### ISSUE THREAD

**Issue by LuoRyan** [EOSIO/eosjs#460]
Hi,
    How to calculate the final transaction hash in the new version of eosjs?
    Your help will be very much appreciated!! Thanks~~

```js
tag@16.0.9
const buf = Fcbuffer.toBuffer(Transaction, txObject)
const tr = Transaction.toObject(txObject)
const transactionId  = createHash('sha256').update(buf).digest().toString('hex')
```

**Comment by c0d3ster** [comment]
If you are in a browser environment, you can use the SubtleCrypto web API to calculate the sha256 hash which can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest). Be sure to create the hash from the serialized transaction (uInt8 array format), and if you want the hex format you can utilize the `arrayToHex` function from `eosjs-serialize`.  I'm closing this for now, but let us know if you have any other questions.  We'll add an example for reference in the future since this will likely be a common question.

**Comment by LuoRyan** [comment]
```js
Crypto.createHash("sha256").update(serializedTransaction).digest("hex");
```
This way you can get a transaction hash

Thank you~~
