### ISSUE TITLE
JsSignatureProvider

### ISSUE THREAD

**Issue by lifan-github** [EOSIO/eosjs#478]
**"eosjs": "^20.0.0-beta3"**
**"react-native": "0.57.8"**

**Describe the bug**
import JsSignatureProvider from 'eosjs/dist/eosjs-jssig'
I import this **'eosjs/dist/eosjs-jssig'**
```
 cannot read property 'prototype' of undefined
```
 Hope someone to help solve, thank you very much!

**Comment by c0d3ster** [comment]
The JsSignatureProvider won't work with React Native due to a dependency on the mobile incompatible `eosjs-ecc` package.  You could potentially write your own signature provider that utilizes a community-created `eosjs-ess-rn` found [here](https://www.npmjs.com/package/eosjs-ecc-rn).  However, this package has not been audited for security or performance implications.  Use at your own risk.
