### ISSUE TITLE
Why does the documentation exist if it is incorrect

### ISSUE THREAD

**Issue by projectoblio** [EOSIO/eosjs#519]
**Version of EOSJS**
eos@fffff and eos@beta3

**Describe the bug**
const JsSignatureProvider = require('eosjs/dist/eosjs-jssig');
const signature = new JsSignatureProvider([privKey]);
` > TypeError: JsSignatureProvider is not a constructor`

**To Reproduce**
try and follow the first 6 lines of the documentation for getting started

**Expected behavior**
works
**Screenshots**

**Desktop (please complete the following information):**
ubuntu 16.04. node 8.14.0

**Smartphone (please complete the following information):**
no

**Additional context**

**Comment by c0d3ster** [comment]
Our branching strategy utilizes a "develop" base branch, which represents the most up-to-date code we are working on.  This is considered `eosjs@edge` which in this case is `eosjs@ffffff`.  This is NOT the same as `eosjs@beta`, which follows the default import convention you used above.  If you are in fact using `eosjs@ffffff`, the homepage README does reflect the current import conventions of the `edge` release.  We chose to remove all default imports/exports, so as you can see [here](https://github.com/EOSIO/eosjs#commonjs) you just need to add brackets to your require statement.

 I do understand how this can be confusing since the [documentation linked in the README](https://eosio.github.io/eosjs/#commonjs) reflects `eosjs@beta` instead, but this will also be updated to reflect our next RC soon.  Thanks for understanding as we move out of beta into eosjs v20.0.0.

**Comment by projectoblio** [comment]
Neither of the options you provided are working using a `require` statement.

**Comment by projectoblio** [comment]
I don't know how i could make it easier to describe. Adding /removing `.default` and brackets doesn't seem to help

**Comment by projectoblio** [comment]
I just want to code for EOS. please help.

**Comment by projectoblio** [comment]
?????????

**Comment by randytorres** [comment]
@projectoblio Run `yarn add eosjs@edge` and import the signature provider like this 

```import { JsSignatureProvider } from 'eosjs/dist/eosjs-jssig'```

**Comment by c0d3ster** [comment]
I just tested the code you posted and it works with the following import statement:
`const JsSignatureProvider = require('eosjs/dist/eosjs-jssig').default; `

I would, however, recommend doing it the way @randytorres mentioned because we plan to pull out of beta very soon and that is the correct syntax.  I went ahead and changed the syntax to `yarn add eosjs@edge` to prevent confusion in the meantime.
