### ISSUE TITLE
Get Table Rows with bool type columns and json: true

### ISSUE THREAD

**Issue by thekevinbrown** [EOSIO/eosjs#540]
**Version of EOSJS**
v20+

**Describe the bug**
When calling `eos.rpc.get_table_rows` with `json: true` on a table that has a `bool` field type, the rows returned come back as `number` type in JS (e.g. `0` or `1` instead of `booleans`). Since there's an obvious type in Javascript for `bool` to map to, I think the results should map to `boolean` instead of `number`.

**To Reproduce**
1. Create a table with a `bool` field.
2. Call `get_table_rows` with `{ json: true }`
3. Actual behaviour: EosJS returns `1` or `0` for the values.

**Expected behavior**
Expected `true` or `false` for the values.

**Additional context**
We're currently working around this by mapping in a wrapper we have for `get_table_rows` but this feels like something EosJS should own.

**Comment by tbfleming** [comment]
eosjs does minimal processing on rpc api results. nodeos produces 1 or 0 for this case.

In this case reprocessing in eosjs would require round-tripping through the abi serializer, since that’d be the only way for eosjs to know where the bools are.

Feel free to file a bug in the eos repo, since that’s where the problem originates.
