### ISSUE TITLE
How to use transaction_context::bill_to_accounts feature 

### ISSUE THREAD

**Issue by f4r4** [EOSIO/eosjs#620]
How to use the Consensus upgrade feature **bill_to_accounts** in eosjs which is mentioned in 
https://github.com/EOSIO/eos/issues/6332 

Please advice

**Comment by jlamarr22** [comment]
@f4r4 I've completed a PoC for you to be able to accomplish this on a local blockchain instance. See https://github.com/EOSIO/tropical-example-web-app/tree/first-authorizer-feature for the example. Some notes:
- This already works in EOSJS if you're integrating with a chain that supports this feature. You only need to ensure that the first signer is the one who you expect to pay for the transaction. This PoC was tested with eosjs `21.0.1.-rc1`.
- Since this example is running on a local chain, the feature needs to be activated: https://github.com/EOSIO/tropical-example-web-app/blob/first-authorizer-feature/eosio/scripts/deploy_contracts.sh#L296
- This is how you set up a multisig relationship: https://github.com/EOSIO/tropical-example-web-app/blob/first-authorizer-feature/eosio/scripts/deploy_contracts.sh#L138 (more info here: https://developers.eos.io/manuals/eos/latest/cleos/how-to-guides/how-to-config-a-multisig-account)
- The first signer here will be the one who pays: https://github.com/EOSIO/tropical-example-web-app/blob/first-authorizer-feature/src/utils/transaction.js#L5
- More info on features you can activate on a chain: https://developers.eos.io/welcome/latest/tutorials/bios-boot-sequence (scroll down to "Enable Features")

Please let me know if you have any questions or you need any other clarification.

**Comment by jlamarr22** [comment]
@nksanthosh
