### ISSUE TITLE
Calling custom contract has unsupported attribute

### ISSUE THREAD

**Issue by sbihgud** [EOSIO/eosjs#637]
![image](https://user-images.githubusercontent.com/20178448/71578333-ae3fd700-2b32-11ea-96b3-28606a42d01a.png) 
![image](https://user-images.githubusercontent.com/20178448/71578339-b4ce4e80-2b32-11ea-953a-ffc3aeda1d83.png)

Is it because of the NodeOS node version or the wrong way of using it?

**Comment by jlamarr22** [comment]
@sbihgud The error you're seeing is because the contract name is invalid. The full error message was updated, so you should see something like: `Name should be less than 13 characters and only contains the following symbol .12345abcdefghijklmnopqrstuvwxyz` Your contract name has an uppercase `C`, which is not allowed.

Somewhat related: https://github.com/EOSIO/eos/issues/2699
