### ISSUE TITLE
What is different between Eos.Testnet and Eos.Localnet?

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eosjs#68]

**Comment by jcalfee** [comment]
* [Testnet](https://github.com/EOSIO/eosjs-api/blob/master/src/testnet.js) uses a publicly hosted httpEndpoint address and [Localnet](https://github.com/EOSIO/eosjs-api/blob/master/src/localnet.js) uses 127.0.0.1
* Eos.Testnet in the browser automatically sets the protocol (`http` or `https`) based on the page's location protocol

These two can probably be combined since they are so alike and should have the same API and data-structures.

**Comment by jcalfee** [comment]
@chris-allnutt what do you think  about removing specialized constructors like Eos.Testnet and Eos.Localnet?  We could have one constructor and documentation.  The end-user is going to need to actively choose which network they will use:

```js
// Local nodeos
eos = Eos({httpEndpoint: 'http://127.0.0.1:8888'})`
```
If we get into supporting multiple networks that have incompatible changes we probably should have separate deployments of eosjs with some common code.

**Comment by chris-allnutt** [comment]
@jcalfee I your above recommendation is good, I think that defaulting values confused people, your above example is much clearer.  Let's deprecate the other methods, and add console.error if people call them.

**Comment by jcalfee** [comment]
I have removed references to "Testnet" and "eos.Testnet" leaving only eos.Localnet so that should help.  I still need consolidate to a single constructor.
