### ISSUE TITLE
if it is support websocket?

### ISSUE THREAD

**Issue by cheng762** [EOSIO/eosjs#770]
Is the client support websocket to connect to remote?

**Comment by jlamarr22** [comment]
@cheng762 You *can* use websockets, but you'd have to use a somewhat hacky approach since nodeos itself doesn't support them. https://github.com/EOSIO/eosio-web-ide/blob/master/webapp provides an example of this approach, which is to continuously ping nodeos here: https://github.com/EOSIO/eosio-web-ide/blob/master/webapp/src/index.tsx#L134
