### ISSUE TITLE
'rm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by varshadqz** [EOSIO/eosjs#820]
I cloned the git repository and running the command `yarn build-web ` in that directory from **visual studio code**. I am getting errors 
```
 yarn run v1.22.5
$ rm -rf dist-web && webpack --config webpack.prod.js && webpack --config webpack.debug.js
'rm' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```

I am new to node.js so getting difficulties with running such commands in VS Code.
How to resolve this issue? I need `eosjs ` files to include in the HTML file.

**Comment by bradlhart** [comment]
The NPM script you are running (https://github.com/EOSIO/eosjs/blob/1cf9bf53d21d3f461f61970d3295ee1fc2ba56d1/package.json#L15) first deletes the output folder `dist-web` if it exists so that the following commands to build the files will be built cleanly, with no old files from the last build.

Since you are running windows, `rm` isn't recognized so you can remove it from the command.  Just make sure to delete the dist-web folder any time you rebuild.

I've added a plugin to webpack to delete the directory so the rm command will be removed in a later release, but in the meantime, removing `rm -rf dist-web && ` from the NPM script will solve your issue.

**Comment by bradlhart** [comment]
This change is now available either at eosjs@edge or eosjs@RC and will soon be released to the latest version of eosjs.
