### ISSUE TITLE
Get Transaction information must provide block number

### ISSUE THREAD

**Issue by mutobui** [EOSIO/eosjs#822]
Why get transaction information must provide block number? Is there any convenient way to do that?
I'm running Cleos version 2.0.9,

**Comment by marcolw** [comment]
Hi @mutobui  Can you elaborate on your issue?
From the doc about getting transaction [here](https://developers.eos.io/manuals/eos/latest/cleos/command-reference/get/transaction), you can get `processed.refBlockNum`.

**Comment by bradlhart** [comment]
It seems that you are using cleos, not eosjs. You might want to reach out to the eos codebase for assistance with cleos if you are still having issues. Closing this issue since this is the eosjs codebase.

However, what @mutobui has posted might help.  Additionally, after sending the transaction at first, you should also receive this information from cleos.
